/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wifipasswords;

import java.awt.Component;

import java.awt.Toolkit;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.util.Iterator;
import java.util.Locale;

import javax.swing.JFrame;

import javax.swing.border.TitledBorder;


import resources.utils.ResourceBundleManager;
import settings.SettingsManager;


/**
 *
 * @author dionysis
 */
public class MyJFrame extends javax.swing.JFrame implements PropertyChangeListener{
    private ArrayList<WifiProfile> profiles;
    private String[] names;
    private final Toolkit thekit;   
    private WifiProfile connectedProfile;
    private NetWorkProfiles network;
    private Locale locale;
    private static final String TOOLBOX_FILE_PATH = System.getenv("APPDATA") + File.separator + "Wi-Fi ToolBox" + File.separator;
    /**
     * Creates new form JFrame
     */
    public MyJFrame(NetWorkProfiles network) {
        locale=ResourceBundleManager.getLocale();
        ResourceBundleManager.addPropertyChangeListener(this);
        
    
        this.network=network;
        thekit = this.getToolkit(); 
        this.setTitle("Wi-Fi Toolbox"); //DINOUME TITLO STO FRAME
        this.setIconImage(thekit.getImage("wifiPass.png")); //DINOUME ICON STO FRAME
        this.profiles=network.getWifiNetworkList();
        names = new String[profiles.size()];
        for (int i = 0; i < profiles.size(); i++) {
            names[i] = profiles.get(i).getName();
        }
        initComponents();
        String c = "\u00A9"+" Dionysis Theodosis";
        jLabel3.setText(c);
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(getBackground());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(ResourceBundleManager.getString("mainTitle"));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel2.setBackground(getBackground());
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, ResourceBundleManager.getString("listOfSavedWifi"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 14), new java.awt.Color(255, 204, 102))); // NOI18N
        jPanel2.setForeground(getBackground());

        jList1.setBackground(getBackground());
        jList1.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jList1.setForeground(new java.awt.Color(102, 204, 255));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() { return names.length; }
            public String getElementAt(int i) { return names[i]; }
        });
        jList1.setSelectionBackground(new java.awt.Color(255, 204, 102));
        jList1.setSelectionForeground(getBackground());
        jList1.addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int selectedIndex = jList1.getSelectedIndex();
                    if (selectedIndex != -1) {
                        String selectedValue = jList1.getSelectedValue();
                        for(int i=0;i<profiles.size();i++){
                            if(profiles.get(i).getName().equals(selectedValue)){
                                jLabel2.setText(profiles.get(i).getPassword());
                                try{
                                    WifiQr qrCode = new WifiQr(profiles.get(i));
                                    setImage(qrCode);
                                }
                                catch(FileNotFoundException ex){
                                    System.out.println("File Not Found for the qr code image");
                                }
                            }
                            if(connectedProfile.getName().equals(selectedValue)){
                                jLabel2.setForeground(new java.awt.Color(102, 255, 153));
                            }
                            else{
                                jLabel2.setForeground(new java.awt.Color(102,204,255));
                            }
                        }

                    }
                }
                TitledBorder titledBorder = (TitledBorder) jPanel3.getBorder();
                titledBorder.setTitle(ResourceBundleManager.getString("selectedWifiPasswordT"));
                jPanel3.setBorder(titledBorder);
                titledBorder = (TitledBorder) jPanel4.getBorder();
                titledBorder.setTitle(ResourceBundleManager.getString("QrImageTitleS"));
                jPanel4.setBorder(titledBorder);
                jPanel3.repaint();
                jPanel3.revalidate();
                jPanel4.repaint();
                jPanel4.revalidate();

            }

        });
        //listSel();
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel3.setBackground(getBackground());
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, ResourceBundleManager.getString("connectedWifiPasswordT"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 14), new java.awt.Color(255, 204, 102))); // NOI18N
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jLabel3.setBackground(getBackground());
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel5.setBackground(getBackground());
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, ResourceBundleManager.getString("connectedWifiNameT"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 14), new java.awt.Color(255, 204, 102))); // NOI18N
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        setConnectedLabels();
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );

        jPanel6.setBackground(getBackground());
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, ResourceBundleManager.getString("QrTitle"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 14), new java.awt.Color(255, 204, 102))); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(356, 283));

        jPanel4.setBackground(getBackground());
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, ResourceBundleManager.getString("QrImageTitleC"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 12), new java.awt.Color(255, 204, 102))); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBackground(getBackground());
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, ResourceBundleManager.getString("QrScanTitle"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 12), new java.awt.Color(255, 204, 102))); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe Print", 0, 10)); // NOI18N
        jButton1.setText(ResourceBundleManager.getString("QrButton"));
        jButton1.setFocusable(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(287, 287, 287))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel3, jPanel5});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel3, jPanel5});

        getContentPane().add(jPanel1, "card2");

        jMenu1.setText(ResourceBundleManager.getString("Menu"));
        jMenu1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N

        jMenu3.setText(ResourceBundleManager.getString("Language"));
        jMenu3.setFont(new java.awt.Font("Segoe Print", 0, 10)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Segoe Print", 0, 10)); // NOI18N
        jMenuItem3.setText(ResourceBundleManager.getString("English"));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);
        jMenu3.add(jSeparator3);

        jMenuItem2.setFont(new java.awt.Font("Segoe Print", 0, 10)); // NOI18N
        jMenuItem2.setText(ResourceBundleManager.getString("Greek"));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenu1.add(jMenu3);
        jMenu1.add(jSeparator1);

        jMenuItem1.setFont(new java.awt.Font("Segoe Print", 0, 10)); // NOI18N
        jMenuItem1.setText(ResourceBundleManager.getString("saveCredImageTitle"));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator2);

        jMenuItem4.setFont(new java.awt.Font("Segoe Print", 0, 10)); // NOI18N
        jMenuItem4.setText(ResourceBundleManager.getString("Exit"));
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText(ResourceBundleManager.getString("Help"));
        jMenu2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem5.setFont(new java.awt.Font("Segoe Print", 0, 10)); // NOI18N
        jMenuItem5.setText(ResourceBundleManager.getString("userGuide"));
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Segoe Print", 0, 10)); // NOI18N
        jMenuItem6.setText(ResourceBundleManager.getString("contactSupport"));
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);
        //this.setJMenuBar(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                            
            QrScanner dialog = new QrScanner(new javax.swing.JFrame(), true,this);
            dialog.setLocationRelativeTo(this);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    Thread closingThread = new Thread(() -> {
                    dialog.clearOnExit();
                  
        
                        });
            closingThread.start();
                }
            });
            dialog.setVisible(true);
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        if(evt.getButton()==1){
            jList1.clearSelection(); 
            setConnectedLabels();
        }
   
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        if(evt.getButton()==1){
            jList1.clearSelection(); 
            setConnectedLabels();
        }
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        locale=new Locale("el");
        ResourceBundleManager.setCurrentLocale(locale);
        SettingsManager.writeSetting("Language", "el");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      
        locale=new Locale("en");
        ResourceBundleManager.setCurrentLocale(locale);
        SettingsManager.writeSetting("Language", "en");
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       if(jList1.isSelectionEmpty()&&connectedProfile!=null){
          saveImage(connectedProfile.getName());
       }
       else if(!jList1.isSelectionEmpty()){
           saveImage(jList1.getSelectedValue());
       }

    };//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        if(evt.getButton()==3){
            ClipboardUtils.copyTextToClipboard(jLabel2.getText());
        }
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        if(evt.getButton()==3){
            ClipboardUtils.copyTextToClipboard(jLabel2.getText());
        }
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
              
             
            
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        HelpDialog dialog = new HelpDialog(this,ResourceBundleManager.getString("userGuide"));
        if(ResourceBundleManager.getLocale().getLanguage().equals("el")){
            dialog.loadHelpDocument(TOOLBOX_FILE_PATH+"help_el.html");
        }
        else if(ResourceBundleManager.getLocale().getLanguage().equals("en")){
            dialog.loadHelpDocument(TOOLBOX_FILE_PATH+"help_en.html");
        }
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
       
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        
        HelpDialog dialog = new HelpDialog(this,ResourceBundleManager.getString("contactSupport"));
        if(ResourceBundleManager.getLocale().getLanguage().equals("el")){
            dialog.loadHelpDocument(TOOLBOX_FILE_PATH+"support_el.html");
        }
        else if(ResourceBundleManager.getLocale().getLanguage().equals("en")){
             dialog.loadHelpDocument(TOOLBOX_FILE_PATH+"support_en.html");
        }
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed
    private void saveImage(String wifiSSID){
        SaveImage panelToSave =new SaveImage(jLabel4.getIcon(),wifiSSID,jLabel2.getText());
        panelToSave.setLocationRelativeTo(this);
        panelToSave.setVisible(true);
    }
    
    private void setConnectedLabels(){
        Iterator<WifiProfile> iterator = profiles.iterator();
        while (iterator.hasNext()) {
            WifiProfile profile = iterator.next();
            if (profile.isConnected()) {
                connectedProfile=profile;
                jLabel5.setText(profile.getName());
                jLabel2.setText(profile.getPassword());
                jLabel2.setForeground(new java.awt.Color(102, 255, 153));
                try{
                    WifiQr qrCode = new WifiQr(profile);
                    setImage(qrCode);
                }
                catch(FileNotFoundException ex){
                    System.out.println("File Not Found for the qr code image");
                }
            }
        }
        if((TitledBorder) jPanel4.getBorder()!=null){
            TitledBorder titledBorder = (TitledBorder) jPanel3.getBorder();
            titledBorder.setTitle(ResourceBundleManager.getString("connectedWifiPasswordT"));
            jPanel3.setBorder(titledBorder);
            titledBorder = (TitledBorder) jPanel4.getBorder();
            titledBorder.setTitle(ResourceBundleManager.getString("QrImageTitleC"));
            jPanel4.setBorder(titledBorder);
            jPanel3.repaint();
            jPanel3.revalidate();
            jPanel4.repaint();
            jPanel4.revalidate();
        }

    }
    /**
     * @param args the command line arguments
     */
    public void setImage(WifiQr qrCode){
        // Create a JLabel to display the QR code image
        
            
            jLabel4.setIcon(qrCode.getImageFile());
        
       
       
    }
    public void setBorder(){
    
    TitledBorder titledBorder = (TitledBorder) jPanel4.getBorder();
    titledBorder.setTitle("Connected Wi-Fi QR Code");
    jPanel4.setBorder(titledBorder);
}
    public void getConnectedProfile(){
            network = new NetWorkProfiles(new CheckConnected().getConnectedProfile());
            if(connectedProfile!=null){
                String prevConnect = connectedProfile.getName();
            }
            connectedProfile=network.getConnected();
            jLabel5.setText(connectedProfile.getName());
            jLabel2.setText(connectedProfile.getPassword());
           
            try{
                WifiQr qrCode = new WifiQr(connectedProfile);
                setImage(qrCode);
            }
            catch(FileNotFoundException ex){
                System.out.println("File Not Found for the qr code image");
            }
            profiles=network.getWifiNetworkList();
            names = new String[profiles.size()];
            for (int i = 0; i < profiles.size(); i++) {
                names[i] = profiles.get(i).getName();
            }
            jList1.setModel(new javax.swing.AbstractListModel<String>() {
                @Override
                public int getSize() { return names.length; }
                @Override
                public String getElementAt(int i) { return names[i]; }
            });
            jList1.clearSelection();
            repaintComponent(jList1);
           
            TitledBorder titledBorder = (TitledBorder) jPanel3.getBorder();
            titledBorder.setTitle(ResourceBundleManager.getString("connectedWifiPasswordT"));
            jPanel3.setBorder(titledBorder);
            titledBorder = (TitledBorder) jPanel4.getBorder();
            titledBorder.setTitle(ResourceBundleManager.getString("QrImageTitleC"));
            jPanel4.setBorder(titledBorder);
            repaintComponent( jPanel3);
            repaintComponent( jPanel4);
            repaintComponent(this);
           
            connectedMessage();
            
    }
    public void connectedMessage(){
        DisplayMessage message = new DisplayMessage((JFrame) this, true);
        message.setLocationRelativeTo(this);
        message.setVisible(true);
      
            
    }
     public void notConnectedMessage(){   
        DisplayMessageNotConnect message = new DisplayMessageNotConnect((JFrame) this, true);
        message.setLocationRelativeTo(this);
        message.setVisible(true);
         
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
       if (evt.getPropertyName().equals("locale")) {
           
           System.out.print("locale change");
            updateLocalizedValues();
        }
    }

    private void updateLocalizedValues() {
        //Title
        jLabel1.setText(ResourceBundleManager.getString("mainTitle"));
        
        if(jList1.isSelectionEmpty()){//if not selected
            //for panel of display passwords
            TitledBorder titledBorder = (TitledBorder) jPanel3.getBorder();
            titledBorder.setTitle(ResourceBundleManager.getString("connectedWifiPasswordT"));
            jPanel3.setBorder(titledBorder);
            //for panel that display qr images
            titledBorder = (TitledBorder) jPanel4.getBorder();
            titledBorder.setTitle(ResourceBundleManager.getString("QrImageTitleC"));
            jPanel4.setBorder(titledBorder);
            repaintComponent( jPanel3);
            repaintComponent( jPanel4);
        }
        else{//if selected
             //for panel of display passwords
            TitledBorder titledBorder = (TitledBorder) jPanel3.getBorder();
            titledBorder.setTitle(ResourceBundleManager.getString("selectedWifiPasswordT"));
            jPanel3.setBorder(titledBorder);
            //for panel that display qr images
            titledBorder = (TitledBorder) jPanel4.getBorder();
            titledBorder.setTitle(ResourceBundleManager.getString("QrImageTitleS"));
            jPanel4.setBorder(titledBorder);
            repaintComponent( jPanel3);
            repaintComponent( jPanel4);
        }
        //for scan button
        jButton1.setText(ResourceBundleManager.getString("QrButton"));
        //for panel that is for list
        TitledBorder titledBorder = (TitledBorder) jPanel2.getBorder();
        titledBorder.setTitle(ResourceBundleManager.getString("listOfSavedWifi"));
        jPanel2.setBorder(titledBorder);
        repaintComponent( jPanel2);
        
        //for connected wifi panel border
        titledBorder = (TitledBorder) jPanel5.getBorder();
        titledBorder.setTitle(ResourceBundleManager.getString("connectedWifiNameT"));
        jPanel5.setBorder(titledBorder);
        repaintComponent( jPanel5);
        
        //for qrcode main panel border
        titledBorder = (TitledBorder) jPanel6.getBorder();
        titledBorder.setTitle(ResourceBundleManager.getString("QrTitle"));
        jPanel6.setBorder(titledBorder);
        repaintComponent( jPanel6);
        
        jMenu1.setText(ResourceBundleManager.getString("Menu"));
        jMenu2.setText(ResourceBundleManager.getString("Help"));
        jMenu3.setText(ResourceBundleManager.getString("Language"));
        jMenuItem2.setText(ResourceBundleManager.getString("Greek"));
        jMenuItem3.setText(ResourceBundleManager.getString("English"));
        jMenuItem4.setText(ResourceBundleManager.getString("Exit"));
        jMenuItem5.setText(ResourceBundleManager.getString("userGuide"));
        jMenuItem6.setText(ResourceBundleManager.getString("contactSupport"));
       
        //for connected with qr code panel border
        titledBorder = (TitledBorder) jPanel7.getBorder();
        titledBorder.setTitle(ResourceBundleManager.getString("QrScanTitle"));
        jPanel7.setBorder(titledBorder);
        repaintComponent( jPanel7);
        jMenuItem1.setText(ResourceBundleManager.getString("saveCredImageTitle"));
        repaintComponent( jMenuItem1);
        
        repaintComponent(this);
    }
    private void repaintComponent(Component panel){
        panel.repaint();
        panel.revalidate();
    }
}
